openapi: 3.1.1
info:
  title: Payment Settlement Attributes (v1)
  version: 1.0.0
  x-profile-id: profiles/payment-settlement/v1/payment-settlement
  description: >
    Attribute schemas for payment settlement (Provider/Payment attributes).
    These attributes are attached to Provider.attributes or Payment.attributes to provide
    settlement account details including bank accounts, IFSC codes, and UPI addresses
    for network participants identified by their subscriber ID.

components:
  schemas:
    ########################################################################
    # PROVIDER/PAYMENT.ATTRIBUTES — PaymentSettlement (pruned)
    ########################################################################
    PaymentSettlement:
      type: object
      additionalProperties: false
      x-jsonld:
        "@context": ./context.jsonld
        "@type": PaymentSettlement
      properties:

        settlementAccounts:
          type: array
          description: List of settlement details (Bank, VPA, etc.) for the entity.
          x-jsonld: { "@id": settlementAccounts }
          items:
            type: object
            additionalProperties: false
            properties:
              beneficiaryId:
                type: string
                description: Subscriber ID of the network participant (BPP or BAP).
                example: "example-bpp.com"
                x-jsonld: { "@id": beneficiaryId }
              accountHolderName:
                type: string
                description: Account holder name.
                example: "EcoPower Charging Solutions"
                x-jsonld: { "@id": accountHolderName }
              accountNumber:
                type: string
                description: Bank account number.
                example: "1234567890123"
                x-jsonld: { "@id": accountNumber }
              ifscCode:
                type: string
                description: Bank IFSC code.
                example: "HDFC0001234"
                x-jsonld: { "@id": ifscCode }
              bankName:
                type: string
                description: Name of the bank.
                example: "HDFC Bank"
                x-jsonld: { "@id": bankName }
              vpa:
                type: string
                description: Virtual Payment Address (UPI ID).
                example: "ecopower@paytm"
                x-jsonld: { "@id": vpa }
              paymentURL:
                type: string
                format: uri
                description: URL for payment processing/redirection.
                example: "https://payments.example.com/pay?transaction_id=123&amount=100"
                x-jsonld: { "@id": "schema:url" }

